### ISSUE TITLE
[FEATURE REQUEST] Timed Inline Invocations

### ISSUE THREAD

**Issue by digiwombat** [ibra/Ibralogue#21]
Rolling this out to a new request per the discussion in #1 

Timed inline invocations are a very helpful way to tie scripting to the text readout. It's especially useful for changing portraits or doing one-off NPC/world animations for effect such as calling a lightning strike to coincide with a certain word.

Example:
> Hello! <<Image: CharacterPortraits/AvaSmiling.png>> I'm happy! <<Image: CharacterPortraits/AvaFrowning.png>> Now I'm sad.

Example 2:
> I think it's important to... <CallLightningStrikeFunction><text-effect=shaking>TIME</texteffect> certain effects with the dialogue.

As discussed previously, this could be tied to the index being read out by having a Dict<int,string> that captures the calls and the index within the string at which to call them.

**Comment by ibra** [comment]
ok so this is a good idea and relatively easy to implement but the problem is that not all implementations of the DialogueManager will necessarily have scrolling dialogue so I'm not sure how to go about implementing this structurally speaking. If you'd happen to have any ideas, feel free to share them.

**Comment by digiwombat** [comment]
As is on the structure, I think there are a few ways to handle it. Creating a GatherInlineFunctions() method and calling it in the DisplayNextLine() method would certainly solve the problem there, then it would just be a question of having people iterate over the Dict of methods to call when they write a DisplayDialogue() function, either by just looping through the Dict in the case of instant display or using the index if it's a typewriter style.

I think if InlineFunctions are going to go in, that's going to have to be something that becomes tightly integrated with the display logic either way and people will just have to understand that any inline functions will flow as a function of the displayed text.

It could also be structurally valuable to extract the scrolling dialogue out to its own class so that display logic can be handled separately. This could be done by having the DialogueManager look for a ScrollingDialogue script on the GameObject and if it doesn't find one, just call the functions all in a line. Of course, then you need to pass the parsed dialogue line and the function dict over to the ScrollingDialogue script and have them handle it there. But it would allow for writing multiple ways of displaying text without having multiple entire Dialogue Managers (separating Display logic from Parsing/Branch Stepthrough logic)

Also, I don't think it does, but do Choice texts currently get parsed for inline variables? Separating out text parsing logic into its own conceptual thing would allow for variables to be parsed anywhere. I've only glanced at stuff at the moment, so I do apologize for not offering a more code heavy answer, but life's been a real roller coaster for me the past few months. Hopefully I'll get some free time to bang out some code to help this along. Love the direction of the project overall though!

**Comment by ibra** [comment]
Thanks!
