### ISSUE TITLE
[FEATURE REQUEST] Triggers

### ISSUE THREAD

**Issue by Xapu1337** [ibra/Ibralogue#5]
**Describe the solution you'd like**
Triggers could be used to call events and could trigger animations while the dialoge is not finished.
Triggers would be look like:
```
~Joe
-Any last words?
!{Animation Start A}
-Let's hope you don't regret it...
```
and the code would look like this:
```cs
void onDialogeTrigger(Dialoge dialoge, string triggerName){
    if(triggerName.equals("Animation Start A")) anim.play();
}
```

**Comment by ibra** [comment]
Function Invocations have been implemented, these are essentially just triggers but better, although they currently only support static function calls. Will consider making a separate issue for instance function invocations.
